configured_endpoints: 21
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/prompt-foundry%2Fprompt-foundry-sdk-4137caec48206e984cbf62aabf1bd1f76c525ac66c0ad16760e49564095b2877.yml
