configured_endpoints: 22
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/prompt-foundry%2Fprompt-foundry-sdk-e8bee356492945c6a488f721b7e79b4f8a55c1edabfed4e2817729017f1ae43d.yml
